// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by `package:ffigen`.
import 'dart:ffi' as ffi;

class PackageEg {
  /// Holds the symbol lookup function.
  final ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
      _lookup;

  /// The symbols are looked up in [dynamicLibrary].
  PackageEg(ffi.DynamicLibrary dynamicLibrary)
      : _lookup = dynamicLibrary.lookup;

  /// The symbols are looked up with [lookup].
  PackageEg.fromLookup(
      ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
          lookup)
      : _lookup = lookup;

  void Temp() {
    return _Temp();
  }

  late final _TempPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function()>>('Temp');
  late final _Temp = _TempPtr.asFunction<void Function()>();

  ffi.Pointer<ffi.Int> Temp1(
    ffi.Pointer<ffi.Char> a,
  ) {
    return _Temp1(
      a,
    );
  }

  late final _Temp1Ptr = _lookup<
      ffi.NativeFunction<
          ffi.Pointer<ffi.Int> Function(ffi.Pointer<ffi.Char>)>>('Temp1');
  late final _Temp1 = _Temp1Ptr.asFunction<
      ffi.Pointer<ffi.Int> Function(ffi.Pointer<ffi.Char>)>();
}
