name: go_gen
description: A starting point for Dart libraries or applications.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: '>=2.19.0 <3.0.0'

dependencies:
  ffi:
  io:

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
  ffigen : 

ffigen:
  name: 'PackageEg'
  output: 'example\Package.dart'
  headers:
    entry-points:
      - 'golangDirectory\c_binding.h'